#!/bin/bash

set -ex

MODE=${1:-"$MODE"}
LERNA="npx lerna"

case ${MODE} in
"canary")
    ${LERNA} publish --canary --preid canary --no-changelog
    ;;
"prerelease")
    ${LERNA} version prerelease --dist-tag next --preid next --no-changelog
    ${LERNA} publish from-git --dist-tag next
    ;;
"release")
    ${LERNA} version --conventional-graduate
    ${LERNA} publish from-git --create-release gitlab
    ;;
"tag-prerelease")
    ${LERNA} publish from-git --dist-tag next
    ;;
"tag-release")
    ${LERNA} publish from-git --create-release gitlab
    ;;
esac
