#!/bin/bash

set -e

HOSTNAME=$1
FILENAME=$2

if [ -f ${FILENAME} ]; then
  if [ ! -d ~/.ssh ]; then
    mkdir -p ~/.ssh
  fi

  eval $(ssh-agent -s)
  ssh-add <(cat ${FILENAME})

  cat <<EOF >~/.ssh/config
  Host git.nativecode.net
    HostName gitssh.nativecode.net
    IdentitiesOnly yes
    IdentityFile ~/.ssh/id_rsa
    PreferredAuthentications publickey
    StrictHostKeyChecking no
    User git
    UserKnownHostsFile=/dev/null
EOF

fi
