#!/bin/bash

BRANCH=$1
ORIGIN=$2
EMAIL=$3

NAME=$(echo ${EMAIL} | grep -oP '[^[:blank:]]+(?=@)')

git config --global user.email ${EMAIL}
git config --global user.name ${NAME}

git remote set-url origin ${ORIGIN}
git checkout ${BRANCH}
