#!/bin/bash

set -e

BRANCH=$1
ORIGIN=${2:-"none"}
EMAIL=${3:-"noreply@nativecode.com"}

NAME=$(echo ${EMAIL} | grep -oP '[^[:blank:]]+(?=@)')

git config --global user.email ${EMAIL}
git config --global user.name ${NAME}

if [ "${ORIGIN}" != "none" ]; then
    git remote set-url origin ${ORIGIN}
fi

git checkout ${BRANCH}
git submodule sync --recursive
git submodule update --init --recursive
